# Autogenerated by devscripts/update-version.py

__version__ = '2023.03.09.203325'

RELEASE_GIT_HEAD = 'f6b14968d1436d363559399e0cf3aa651e7e12af'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
