# Autogenerated by devscripts/update-version.py

__version__ = '2023.03.07.210948'

RELEASE_GIT_HEAD = 'a611711871408cdd90aaa3b850d7a74739e9c07a'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
