# Autogenerated by devscripts/update-version.py

__version__ = '2023.03.09.033920'

RELEASE_GIT_HEAD = 'f76a868da4a39b3e95bc5bca977eab67e54ee872'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
